server:
  port: 8085

spring:
  application:
    name: restaurant
  datasource:
    url: jdbc:h2:~/ifood-restaurant
    username: ifooduser
    password: ifoodpass
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create
