server:
  port: 8084

spring:
  application:
    name: menus
  datasource:
    url: jdbc:h2:~/ifood-menu
    username: ifooduser
    password: ifoodpass
    platform: h2
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

    hibernate:
      ddl-auto: create
